version: '2'
services:
  influxdb:
    image: influxdb
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8125:8125/udp"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
